name:    instagram-scraper
version: "0.0.1"

dependencies:
- base
- directory
- bytestring
- text
- aeson
- http-client-tls
- http-conduit

executables:
  instagramhs:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N