name:    instagram-scraper
version: "0.0.1.0"

dependencies:
- base
- aeson
- bytestring
- directory
- http-client-tls
- http-conduit
- text

executables:
  instagramhs:
    main: Main.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
